version: '3.9'
name: 'progy-back-end'

services:
  postgres:
    image: postgres:latest
    container_name: progy-postgres
    restart: always
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - pg-data:/data/postgres
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    container_name: progy-redis
    restart: always
    ports:
      - 6379:${REDIS_PORT}
    volumes:
      - redis-data:/data/redis
    
volumes:
  pg-data:
  redis-data: